name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  ci:
    name: Build and Lint
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: "Ubuntu Clang", os: ubuntu-24.04, compiler: clang, build-type: Debug }
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang \
            clang-tidy \
            clang-format \
            cppcheck \
            cmake \
            ninja-build \
            git

      - name: Setup MSVC environment
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Cache build directory
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/build
          key: ${{ runner.os }}-build-${{ matrix.config.build-type }}-${{ hashFiles('CMakeLists.txt', 'CMakePresets.json', 'src/**', 'include/**') }}
          restore-keys: ${{ runner.os }}-build-${{ matrix.config.build-type }}-

      - name: CMake
        run: |
            cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -G Ninja
        
      - name: Build (Debug)
        run: cmake --build build --config Debug --parallel 4
      
      - name: Cppcheck
        run: make check
      
      - name: clang-tidy
        run: make lint

      - name: clang-format
        run: make tidy
