name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  LIBSODIUM_VERS: 1.0.22

permissions:
  contents: read

jobs:
  ci:
    name: Build and Lint
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: "Ubuntu Clang", os: ubuntu-24.04, compiler: clang, build-type: Debug }
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang-18 \
            clang-tidy-18 \
            clang-format-18 \
            cppcheck \
            cmake \
            ninja-build \
            git \
            libc++-18-dev \
            libc++abi-18-dev \
            pkg-config \
            libargon2-dev \
            libfmt-dev
          sudo ln -sf /usr/bin/clang-format-18 /usr/local/bin/clang-format
          sudo ln -sf /usr/bin/clang-tidy-18 /usr/local/bin/clang-tidy

      - name: Cache libsodium installation
        id: cache-libsodium
        uses: actions/cache@v4
        with:
          path: ~/libsodium
          key: libsodium-${{ env.LIBSODIUM_VERS }}-${{ runner.os }}

      - if: ${{ steps.cache-libsodium.outputs.cache-hit != 'true' && runner.os == 'Linux' }}
        name: Install libsodium from source
        run: |
          curl -L -o libsodium-${{ env.LIBSODIUM_VERS }}.tar.gz https://github.com/jedisct1/libsodium/releases/download/${{ env.LIBSODIUM_VERS }}-RELEASE/libsodium-${{ env.LIBSODIUM_VERS }}.tar.gz
          tar -xvzf libsodium-${{ env.LIBSODIUM_VERS }}.tar.gz
          cd libsodium-${{ env.LIBSODIUM_VERS }}
          ./configure --prefix="$HOME/libsodium"
          make -j$(nproc)
          make install

      - name: Setup MSVC environment
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: CMake
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_CXX_COMPILER=clang++-18 \
            -DCMAKE_C_COMPILER=clang-18 \
            -DCMAKE_CXX_FLAGS="-stdlib=libc++" \
            -DCMAKE_EXE_LINKER_FLAGS="-stdlib=libc++" \
            -DCMAKE_PREFIX_PATH=$HOME/libsodium \
            -G Ninja

      - name: Build (Debug)
        run: cmake --build build --config Debug --parallel 4
      
      - name: Cppcheck
        run: make check
      
      - name: clang-tidy
        run: make lint

      - name: clang-format
        run: make format
